# permissions for end users to view ranchersyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rancher-config-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: ranchersync-viewer-role
rules:
- apiGroups:
  - rancher.sync.io
  resources:
  - ranchersyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rancher.sync.io
  resources:
  - ranchersyncs/status
  verbs:
  - get
