---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rancher.sync.io
  resources:
  - ranchersyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rancher.sync.io
  resources:
  - ranchersyncs/finalizers
  verbs:
  - update
- apiGroups:
  - rancher.sync.io
  resources:
  - ranchersyncs/status
  verbs:
  - get
  - patch
  - update
